package GUI;




import Backend.*;
import template_packet.error_template;


import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author stel
 */
public   class chooseCv extends javax.swing.JFrame {

    
     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int Key_is_pressed = 0;
     private  ArrayList<CV> cvList;
    /**
     * Creates new form Choose_one
     */
    public chooseCv() {
        initComponents();
        cvList=new ArrayList<CV>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        func_Button = new javax.swing.JRadioButton();
        Chronological_Button = new javax.swing.JRadioButton();
        Compine_BUtton3 = new javax.swing.JRadioButton();
        next_Button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CV Maker");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonGroup1.add(func_Button);
        func_Button.setText("Functional CV");
        func_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                func_ButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(Chronological_Button);
        Chronological_Button.setText("Chronological CV");
        Chronological_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chronological_ButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(Compine_BUtton3);
        Compine_BUtton3.setText("Combined CV");
        Compine_BUtton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Compine_BUtton3ActionPerformed(evt);
            }
        });

        next_Button.setText("next");
        next_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_ButtonActionPerformed(evt);
            }
        });

        exit_button.setText("exit");
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Choose  one of the following template for your CV and press next :");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(func_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Chronological_Button)
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Compine_BUtton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(next_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exit_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(func_Button)
                    .addComponent(Chronological_Button)
                    .addComponent(Compine_BUtton3))
                .addGap(51, 51, 51)
                .addComponent(next_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exit_button)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void func_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_func_ButtonActionPerformed
        // TODO add your handling code here:
               Key_is_pressed = 1;

    }//GEN-LAST:event_func_ButtonActionPerformed

    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_buttonActionPerformed

    private void Chronological_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chronological_ButtonActionPerformed
        // TODO add your handling code here:e
        Key_is_pressed = 2;
    }//GEN-LAST:event_Chronological_ButtonActionPerformed

  
    
    private void next_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_ButtonActionPerformed
        // TODO add your handling code here:

      
          if (Key_is_pressed==0){
            
            error_template s = new error_template();
            s.setVisible(true);
      
            
        }else if(Key_is_pressed == 1){
            CV cv1 = new CV();
            cvList.add(cv1);
            cvTemplate func = new cvTemplate(cv1);
            func.setPanel(Key_is_pressed);
            func.setVisible(true);


               
        }else if(Key_is_pressed == 2){
            
             CV cv2 = new CV();
             cvList.add(cv2);
           cvTemplate chron = new cvTemplate(cv2);

             chron.setPanel(Key_is_pressed);
             chron.setVisible(true);
             
           
              
        }else if(Key_is_pressed == 3){
           CV cv3 = new CV();
           cvList.add(cv3);
           cvTemplate comp = new cvTemplate(cv3);
           comp.setPanel(Key_is_pressed);
           comp.setVisible(true);
           
        }
    
       
        
    }//GEN-LAST:event_next_ButtonActionPerformed
     
   
    private void Compine_BUtton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Compine_BUtton3ActionPerformed
        // TODO add your handling code here:
           Key_is_pressed= 3;
    }//GEN-LAST:event_Compine_BUtton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
                 

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chooseCv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chooseCv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chooseCv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chooseCv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
          
            public void run() {
                
                new chooseCv().setVisible(true);
            }
        }
        );

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Chronological_Button;
    private javax.swing.JRadioButton Compine_BUtton3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton exit_button;
    private javax.swing.JRadioButton func_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton next_Button;
    // End of variables declaration//GEN-END:variables
}
